[package]
name = "roget"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.release]
debug = true

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }
mimalloc = "0.1.29"
once_cell = "1"
